// <auto-generated />
using CustomerPlansAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerPlansAPI.Migrations
{
    [DbContext(typeof(CustomerPlansDbContext))]
    [Migration("20230607093308_plansdbsetup")]
    partial class plansdbsetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerPlansAPI.Model.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HalfYearlyCost")
                        .HasColumnType("float");

                    b.Property<int>("MaxDeviceSupport")
                        .HasColumnType("int");

                    b.Property<double>("MonthlyCost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuarterlyCost")
                        .HasColumnType("float");

                    b.Property<double>("YearlyCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CustomerPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
